### PR TITLE
Update README.md - Replaced Sublist3r with updated fork

### PR DESCRIPTION
**Pull request by hellodarkness**
The Sublist3r in the list is an abandoned project that no longer works. Updated the list with a fork that has fixed many of the issues with the abandoned project.

### CODE REVIEW

**Comment by vavkamil** [comment]
>  that has fixed many of the issues

Looks like you fixed mostly just the Virustotal integration?
https://github.com/aboul3la/Sublist3r/compare/master...huntergregal:Sublist3r:master

**Comment by hellodarkness** [comment]
Hi, it's not my fork. I'm just a user. I (and many others, based on the issues on the old Sublist3r repo) was having issues with it not returning any subs, even for domains that are known to have several. That fork was recommended to me and it working for me so I thought I'd suggest it.

**Comment by vavkamil** [comment]
Thanks for the clarification, since there is 1995 forks https://github.com/aboul3la/Sublist3r/forks I have no idea which one to add to the list

**Comment by hellodarkness** [comment]
Fair. I suggested the one above because it's recent, the developer has been commenting on issues on the original, and it's working.

There's another, more active fork:
https://github.com/fleetcaptain/Turbolist3r

But I'm not as familiar with it.

**Pull request closed without merging**
